// swift-tools-version: 5.9
import PackageDescription

// GENERATED by scripts/release-ios.sh for release 1.2.6.
// Source manifest lives on the main branch; release tags carry this
// thin binary form so consumers pull the prebuilt XCFramework.
let package = Package(
    name: "QTrustScanner",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "QTrustScanner", targets: ["QTrustScanner"]),
    ],
    targets: [
        .binaryTarget(
            name: "QTrustScanner",
            url: "https://github.com/qtrust-id/qtrust-sdk-scanner/releases/download/1.2.6/QTrustScanner-1.2.6.xcframework.zip",
            checksum: "538465b40dd3e435b0fd8b49188e1911875005e42afc95b28a0bf8d21eef3dfc"
        ),
    ]
)
