// swift-tools-version: 5.9
import PackageDescription

// GENERATED by scripts/release-ios.sh for release 1.1.0.
// Source manifest lives on the main branch; release tags carry this
// thin binary form so consumers pull the prebuilt XCFramework.
let package = Package(
    name: "QTrustScanner",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "QTrustScanner", targets: ["QTrustScanner"]),
    ],
    targets: [
        .binaryTarget(
            name: "QTrustScanner",
            url: "https://github.com/qtrust-id/qtrust-sdk-scanner/releases/download/1.1.0/QTrustScanner-1.1.0.xcframework.zip",
            checksum: "20496d41a71240d75183a407328518a0889c26544cccf81e77b2d3595569cdad"
        ),
    ]
)
