// swift-tools-version: 5.9
import PackageDescription

// GENERATED by scripts/release-ios.sh for release 1.0.1.
// Source manifest lives on the main branch; release tags carry this
// thin binary form so consumers pull the prebuilt XCFramework.
let package = Package(
    name: "QTrustScanner",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "QTrustScanner", targets: ["QTrustScanner"]),
    ],
    targets: [
        .binaryTarget(
            name: "QTrustScanner",
            url: "https://github.com/syahfei-venturo/sdk-ios/releases/download/1.0.1/QTrustScanner-1.0.1.xcframework.zip",
            checksum: "6e25bb1eb6b2cf375e0de901b111fe3972aa83725d9d51e175c381402acc1978"
        ),
    ]
)
